baseURL = 'https://www.marzahn-pride.de/'
languageCode = 'ru-RU'
title = 'Marzahn Pride 2026'
defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true
[languages]
  [languages.ru]
    title = 'Marzahn Pride 2026'
    languageCode = 'ru-RU'
    languageName = 'RU'
    weight = 1
    contentDir = 'content/ru'
    [languages.ru.menu]
    [[languages.ru.menu.footer]]
      name = 'Выходные данные'
      url = '/impressum'
      weight = 1
    [[languages.ru.menu.footer]]
      name = 'Политика безопасности'
      url = '/datenschutz'
      weight = 2
  [languages.de]
    title = 'Marzahn Pride 2026'
    languageName = 'DE'
    languageCode = 'de-DE'
    weight = 2
    contentDir = 'content/de'
    [languages.de.menu]
    [[languages.de.menu.footer]]
      name = 'Impressum'
      url = '/de/impressum'
      weight = 1
    [[languages.de.menu.footer]]
      name = 'Datenschutz'
      url = '/de/datenschutz'
      weight = 2
  [languages.en]
    title = 'Marzahn Pride 2026'
    languageName = 'EN'
    languageCode = 'en-US'
    weight = 3
    contentDir = 'content/en'
    [languages.en.menu]
    [[languages.en.menu.footer]]
      name = 'Impressum'
      url = '/en/impressum'
      weight = 1
    [[languages.en.menu.footer]]
      name = 'Privacy'
      url = '/en/datenschutz'
      weight = 2
  [languages.uk]
      title = 'Marzahn Pride 2026'
      languageName = 'UK'
      languageCode = 'uk-UA'
      weight = 4
      contentDir = 'content/uk'
      [languages.uk.menu]
      [[languages.uk.menu.footer]]
        name = 'Відбиток'
        url = '/uk/impressum'
        weight = 1
      [[languages.uk.menu.footer]]
        name = 'Політика конфіденційності'
        url = '/uk/datenschutz'
        weight = 2